CREATE DATABASE DBProcessoSeletivo2RP;
GO

USE DBProcessoSeletivo2RP;
GO

CREATE TABLE TIPOUSUARIO (
	IdTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	tipo VARCHAR(256) NOT NULL
);
GO

CREATE TABLE USUARIO(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(256) NOT NULL,
	senha VARCHAR(62) NOT NULL,
	situacao BIT NOT NULL
);
GO